### ISSUE TITLE
why not use the latest elasticsearch?

### ISSUE THREAD

**Issue by riverbaby** [a-goryachev/docker-swarm-elasticsearch#2]
you do a great job, but  i notice that the version of elasticsearch is 5.2.2,  the newest is 5.4.0

**Comment by a-goryachev** [comment]
Hi @riverbaby . Thanks for the note. I updated the source code to use elasticsearch 5.4.0.
To update your swarm cluster please run a command `docker service update <your_service> --image agoryachev/docker-swarm-elasticsearch:5.4.0`

**Comment by riverbaby** [comment]
ok, thank you very much.
