### ISSUE TITLE
How to connect logstash and kibana to ES

### ISSUE THREAD

**Issue by yogeek** [a-goryachev/docker-swarm-elasticsearch#5]
Hello,

Thank you for your solution, I blocked on deploying an ES cluster in Docker Swarm for a while.
Your solution works for ElasticSearch globally replicated on Swarm cluster.
However, I also have a Logstash and Kibana service in the Swarm and before your solution (when I had only one ES node), these services were configured to find ES with the `elasticsearch` name (name of the service in the docker-compose in which the 3 components share the same overlay network).

But now, Logstash and Kibana can't find the `elasticsearch` service anymore... is it because your `es-docker` script set the `network.publish_host` of the master to the IP of the container ?

How can I configure logstash and kibana to find elasticsearch service in your configuration ?
Thank you

**Comment by a-goryachev** [comment]
Hi, you need to configure Logstash and Kibana with an external URL of elasticsearch service. For example, you have 3 servers in swarm where 3 instances of elasticsearch service is running. The servers' domain names are: srv-1.myhost.com, srv-2.myhost.com, srv-3.myhost.com. You should configure kibana or logstash with any of these hosts (e.g. elasticsearch_url=http://srv-1.myhost.com:9200). Or better use multiple DNS.
Make sure that your elasticsearch service in swarm configured with `-publish 9200:9200` option.

Another option, if you want to have logstash, kibana and elasticsearch in the same swarm cluster you need to configure all these services with the same network e.g. `--network=elastic_cluster` and configure logstash and kibana with elasticsearch_url=http://<elasticsearch_service_name>:9200.
